import Head from "next/head";
import { Accordion, Container } from "~/components";
import { FAQ } from "~/constants/faq";

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "What materials should I upload for best results?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Upload any documents that describe your product design or manufacturing process at any maturity level. For Design FMEA (DFMEA): product requirements and specifications, design descriptions, drawings, schematics and interfaces, known issues, discrepancy reports, or lessons learned. For Process FMEA (PFMEA): work instructions and standard operating procedures, process flow diagrams and layouts, product descriptions or datasheets for functional context. More detailed and structured inputs lead to more accurate and relevant FMEA results.",
      },
    },
    {
      "@type": "Question",
      name: "What do I get as output?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "You receive a complete FMEA Excel file structured according to AIAG & VDA industry practices. It supports both Design FMEA (DFMEA) and Process FMEA (PFMEA), delivered in a review-ready Excel format. Includes structure, functions, failure chains, current controls, ratings, and recommended actions.",
      },
    },
    {
      "@type": "Question",
      name: "How are Severity, Occurrence, Detection (S/O/D) and Action Priority (AP) calculated? Can I change them?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Severity, Occurrence, and Detection (S/O/D) ratings are generated by the AI based on embedded AIAG & VDA rating logic. Action Priority (AP) is automatically assigned using the official AIAG & VDA Action Priority tables. All values in the Excel file are fully editable and should be reviewed, adjusted, and approved by your cross-functional team.",
      },
    },
    {
      "@type": "Question",
      name: "When should I perform an FMEA?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "FMEA is most effective when performed early in design and process development. Early DFMEA and PFMEA help identify risks before they become costly, drive requirements and controls early in the project lifecycle, and improve schedule predictability and cost efficiency. FMEA performed later can still add value, but design and process changes become significantly more expensive.",
      },
    },
    {
      "@type": "Question",
      name: "Can I manage my full FMEA lifecycle in this app?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "No. For security and data-privacy reasons, the app does not function as a long-term FMEA management system. Uploaded documents are deleted immediately after analysis, and generated FMEA files are not stored after download. This approach minimizes data retention and ensures your intellectual property remains under your control.",
      },
    },
    {
      "@type": "Question",
      name: "How do I validate the quality of the AI-generated FMEA?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Each FMEA entry includes explicit AI rationale in the Excel output, with a strong focus on grounding current prevention and detection controls in the uploaded documents. This allows you to verify whether identified controls are objectively supported by your documentation, review the logic behind failure modes and effects, and quickly identify assumptions, gaps, or areas requiring engineering judgment. Final validation and approval must always be performed by qualified engineers.",
      },
    },
    {
      "@type": "Question",
      name: "Can I use the output directly for a certification audit?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "No. The generated FMEA is a high-quality draft, not a final certification record. Before any audit or submission, human review and approval are required, ratings, actions, and responsibilities must be confirmed, and internal FMEA procedures must be applied. Final responsibility remains with your organization.",
      },
    },
    {
      "@type": "Question",
      name: "Can I try the tool for free?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "Yes. We offer 25 free credits to every new user upon registration—no credit card required. You can use these credits to generate your first FMEA entries and test the full capabilities of our AI workflow before purchasing a plan.",
      },
    },
  ],
};

const Faq = () => {
  return (
    <>
      <Head>
        <script
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
          type="application/ld+json"
        />
      </Head>
      <section m="sm:b-30 b-15" p="y-10">
        <Container>
          <div flex="~ col items-center" gap="6" mb="sm:10 8" text="center">
            <h2 line-height="tight" text="center lg:3rem 2rem gray-dark ">
              Do you have any questions?
            </h2>
          </div>

          <div flex="~ col" max-w="800px" mx="auto">
            {FAQ.map((item, idx) => (
              <Accordion
                id={`homepage-faq-${idx}`}
                key={idx}
                title={item.question}
              >
                <div overflow="hidden">{item.answer}</div>
              </Accordion>
            ))}
          </div>
        </Container>
      </section>
    </>
  );
};

export default Faq;
