import { JSX } from 'react'

export interface FaqType {
  question: string
  answer: JSX.Element
  hash?: string
}

export const FAQ = [
  {
    question: 'What materials should I upload for best results?',
    answer: (
      <div space-y="3">
        <p>
          Upload any documents that describe your{' '}
          <span font="semibold">product design or manufacturing process</span>,
          product design or manufacturing process, at any maturity level.
        </p>

        <div space-y="2">
          <p font="semibold">For Design FMEA (DFMEA):</p>

          <ul list="disc" pl="8" space-y="2">
            <li>Product requirements and specifications</li>
            <li>Design descriptions, drawings, schematics, and interfaces</li>
            <li>Known issues, discrepancy reports, or lessons learned</li>
          </ul>
        </div>

        <div space-y="2">
          <p font="semibold">For Process FMEA (PFMEA):</p>

          <ul list="disc" pl="8" space-y="2">
            <li>Work instructions and standard operating procedures</li>
            <li>Process flow diagrams and layouts</li>
            <li>Product descriptions or datasheets for functional context</li>
          </ul>
        </div>

        <p>
          More detailed and structured inputs lead to more accurate and relevant
          FMEA results.
        </p>
      </div>
    )
  },
  {
    question: 'What do I get as output?',
    answer: (
      <div space-y="3">
        <p>
          You receive a <span font="semibold">complete FMEA Excel file</span>,
          structured according to <span font="semibold">AIAG & VDA</span>{' '}
          industry practices.
        </p>

        <ul list="disc" pl="8" space-y="2">
          <li>
            Supports both <span font="semibold">Design FMEA (DFMEA)</span> and{' '}
            <span font="semibold">Process FMEA (PFMEA)</span>
          </li>
          <li>
            Delivered in a{' '}
            <span font="semibold">review-ready Excel format</span>
          </li>
          <li>
            Includes structure, functions, failure chains, current controls,
            ratings, and recommended actions
          </li>
        </ul>

        <p>
          The output is intended to accelerate engineering work and support
          structured FMEA reviews.
        </p>
      </div>
    )
  },
  {
    question:
      'How are Severity, Occurrence, Detection (S/O/D) and Action Priority (AP) calculated? Can I change them?',
    answer: (
      <div space-y="3">
        <ul list="disc" pl="8" space-y="2">
          <li>
            <span font="semibold">
              Severity, Occurrence, and Detection (S/O/D)
            </span>{' '}
            ratings are generated by the AI based on embedded{' '}
            <span font="semibold">AIAG & VDA</span> rating logic.
          </li>
          <li>
            <span font="semibold">Action Priority (AP)</span> is automatically
            assigned using the official{' '}
            <span font="semibold">AIAG & VDA Action Priority tables</span>.
          </li>
        </ul>

        <p>
          All values in the Excel file are{' '}
          <span font="semibold">fully editable</span> and should be reviewed,
          adjusted, and approved by your cross-functional team.
        </p>
      </div>
    )
  },
  {
    question: 'When should I perform an FMEA?',
    answer: (
      <div space-y="3">
        <p>
          FMEA is most effective when performed{' '}
          <span font="semibold">early in design and process development</span>.
        </p>

        <p>Early DFMEA and PFMEA help:</p>

        <ul list="disc" pl="8" space-y="2">
          <li>Identify risks before they become costly</li>
          <li>
            Drive requirements and controls early in the project lifecycle
          </li>
          <li>Improve schedule predictability and cost efficiency</li>
        </ul>

        <p>
          FMEA performed later can still add value, but design and process
          changes become significantly more expensive.
        </p>
      </div>
    )
  },
  {
    question: 'Can I manage my full FMEA lifecycle in this app?',
    answer: (
      <div space-y="3">
        <p>
          No. For security and data-privacy reasons, the app does not function
          as a long-term FMEA management system.
        </p>

        <ul list="disc" pl="8" space-y="2">
          <li>
            Uploaded documents are{' '}
            <span font="semibold">deleted immediately</span> after analysis
          </li>
          <li>
            Generated FMEA files are <span font="semibold">not stored</span>{' '}
            after download
          </li>
        </ul>

        <p>
          This approach minimizes data retention and ensures your intellectual
          property remains under your control.
        </p>
      </div>
    )
  },
  {
    question: 'How do I validate the quality of the AI-generated FMEA?',
    answer: (
      <div space-y="3">
        <p>
          Each FMEA entry includes{' '}
          <span font="semibold">explicit AI rationale in the Excel output</span>
          , with a strong focus on{' '}
          <span font="semibold">
            grounding current prevention and detection controls
          </span>{' '}
          in the uploaded documents.
        </p>

        <p>This allows you to:</p>

        <ul list="disc" pl="8" space-y="2">
          <li>
            Verify whether{' '}
            <span font="semibold">
              identified controls are objectively supported
            </span>{' '}
            by your documentation
          </li>
          <li>
            Review the{' '}
            <span font="semibold">logic behind failure modes and effects</span>{' '}
            in the context of the provided information
          </li>
          <li>
            Quickly identify{' '}
            <span font="semibold">
              assumptions, gaps, or areas requiring engineering judgment
            </span>
          </li>
        </ul>

        <p>
          While the AI accelerates analysis and highlights risk areas,{' '}
          <span font="semibold">
            final validation and approval must always be performed by qualified
            engineers
          </span>
          .
        </p>
      </div>
    )
  },
  {
    question: 'Can I use the output directly for a certification audit?',
    answer: (
      <div space-y="3">
        <p>
          No. The generated FMEA is a{' '}
          <span font="semibold">high-quality draft</span>, not a final
          certification record.
        </p>

        <p>Before any audit or submission:</p>

        <ul list="disc" pl="8" space-y="2">
          <li>Human review and approval are required</li>
          <li>Ratings, actions, and responsibilities must be confirmed</li>
          <li>Internal FMEA procedures must be applied</li>
        </ul>

        <p>
          The app accelerates FMEA creation and improves consistency, but{' '}
          <span font="semibold">
            final responsibility remains with your organization
          </span>
          .
        </p>
      </div>
    )
  },
  {
    question: 'Can I try the tool for free?',
    answer: (
      <div space-y="3">
        <p>
          Yes. We offer 25 free credits to every new user upon registration—no
          credit card required. You can use these credits to generate your first
          FMEA entries and test the full capabilities of our AI workflow before
          purchasing a plan.
        </p>
      </div>
    )
  }
]
