import { Container, SeoHead } from '~/components'

const TermsOfUse = () => {
  return (
    <>
      <SeoHead
        canonical="https://fmeatool.ai/terms-of-use"
        description="Read the Terms of Use for the fmeatool.ai website operated by Maudlin Works, LLC."
        title="Terms of Use | FMEA Tool"
      />

      <div py="lg:40 30">
        <Container>
          <div
            bg="gray-lighter"
            leading="relaxed"
            max-w="5xl"
            mx="auto"
            p="y-10 sm:x-10 x-4"
            rounded="2xl"
            shadow="xl"
            text="sm:base sm">
            <div mb="12" text="center">
              <h1
                color="gray-darker "
                font="bold"
                mb="4"
                text="3xl sm:5xl"
                tracking="tight">
                Terms of Use
              </h1>

              <p text="base gray-dark">Last updated: January 12, 2026</p>
            </div>

            <div
              className="[&_h2]:color-gray-darker [&_h2]:font-semibold [&_h2]:mb-4 [&_h2]:text-xl sm:3xl "
              color="gray-dark"
              space-y="8">
              <div>
                <h2>Agreement to Terms</h2>
                <p>
                  Welcome to <strong>fmeatool.ai</strong> (the
                  &quot;Site&quot;), operated by{' '}
                  <strong>Maudlin Works, LLC</strong> (&quot;Company,&quot;
                  &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). By
                  accessing or using this Site, you agree to be bound by these
                  Terms of Use. If you do not agree to these terms, please do
                  not use the Site.
                </p>
              </div>

              <div>
                <h2>Informational Purpose Only</h2>
                <p>
                  The content provided on this Site is for general informational
                  and marketing purposes regarding our FMEA Tool software.
                  Please note that the actual software service is hosted
                  separately at{' '}
                  <span className="font-semibold">app.fmeatool.ai</span> and is
                  subject to its own separate Terms of Service.
                </p>
              </div>

              <div>
                <h2>Intellectual Property</h2>
                <p>
                  All content, features, and functionality on this Site
                  (including but not limited to the &quot;FMEA Tool&quot; brand,
                  logos, 3D graphics, text, and design) are the exclusive
                  property of Maudlin Works, LLC and are protected by United
                  States and international copyright, trademark, and other
                  intellectual property laws. You may not reproduce, distribute,
                  or create derivative works from any part of this Site without
                  our express written permission.
                </p>
              </div>

              <div>
                <h2>Disclaimer Regarding AI Features</h2>
                <p>
                  Our Site describes software that utilizes Artificial
                  Intelligence (AI). While we strive to describe our product
                  accurately, AI technologies are probabilistic in nature and
                  may produce errors, omissions, or unexpected outputs. We do
                  not guarantee that the marketing descriptions on this Site
                  will align perfectly with every output generated by the
                  software.
                </p>
                <p mt="2">
                  <strong>Important:</strong> FMEA (Failure Mode and Effects
                  Analysis) is used in safety-critical engineering contexts. Any
                  AI-generated FMEA outputs from our software are intended as a
                  starting point and must be reviewed, validated, and approved
                  by qualified engineers before use. Maudlin Works, LLC assumes
                  no liability for engineering decisions, safety assessments, or
                  compliance determinations made based on information presented
                  on this marketing site or outputs from the software.
                </p>
              </div>

              <div>
                <h2>Disclaimer of Warranties</h2>
                <p>
                  THE SITE, ITS CONTENT, AND ANY SERVICES OR PRODUCTS OBTAINED
                  THROUGH THE SITE ARE PROVIDED ON AN &quot;AS IS&quot; AND
                  &quot;AS AVAILABLE&quot; BASIS, WITHOUT ANY WARRANTIES OF ANY
                  KIND, EITHER EXPRESS OR IMPLIED. NEITHER MAUDLIN WORKS, LLC
                  NOR ANY PERSON ASSOCIATED WITH THE COMPANY MAKES ANY WARRANTY
                  OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY,
                  RELIABILITY, QUALITY, ACCURACY, OR AVAILABILITY OF THE SITE OR
                  ANY AI-GENERATED OUTPUTS.
                </p>
                <p mt="2">
                  TO THE FULLEST EXTENT PROVIDED BY LAW, THE COMPANY HEREBY
                  DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR
                  IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO
                  ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, AND
                  FITNESS FOR A PARTICULAR PURPOSE.
                </p>
              </div>

              <div>
                <h2>Limitation of Liability</h2>
                <p>
                  TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT
                  SHALL MAUDLIN WORKS, LLC, ITS AFFILIATES, OFFICERS, DIRECTORS,
                  EMPLOYEES, AGENTS, OR LICENSORS BE LIABLE FOR ANY INDIRECT,
                  PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY
                  DAMAGES, INCLUDING WITHOUT LIMITATION DAMAGES FOR LOSS OF
                  PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES,
                  ARISING OUT OF OR RELATING TO YOUR USE OF THE SITE OR
                  SERVICES.
                </p>
                <p mt="2">
                  IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS
                  EXCEED THE AMOUNT PAID BY YOU TO US DURING THE TWELVE (12)
                  MONTHS PRIOR TO THE CLAIM, OR ONE HUNDRED US DOLLARS ($100),
                  WHICHEVER IS GREATER.
                </p>
              </div>

              <div>
                <h2>Indemnification</h2>
                <p>
                  You agree to defend, indemnify, and hold harmless Maudlin
                  Works, LLC, its affiliates, licensors, and service providers,
                  and its and their respective officers, directors, employees,
                  contractors, agents, licensors, suppliers, successors, and
                  assigns from and against any claims, liabilities, damages,
                  judgments, awards, losses, costs, expenses, or fees (including
                  reasonable attorneys&apos; fees) arising out of or relating
                  to: (a) your violation of these Terms; (b) your use of the
                  Site or services; (c) your reliance on any AI-generated
                  content or FMEA outputs; or (d) any engineering, safety, or
                  compliance decisions made using information from this Site or
                  our services.
                </p>
              </div>

              <div>
                <h2>Service Availability</h2>
                <p>
                  We do not guarantee that the Site or our services will be
                  available at all times or without interruption. We reserve the
                  right to modify, suspend, or discontinue any part of the Site
                  or services at any time without notice. We shall not be liable
                  to you or any third party for any modification, suspension, or
                  discontinuance of the Site or services.
                </p>
              </div>

              <div>
                <h2>Account Termination</h2>
                <p>
                  We reserve the right, in our sole discretion, to terminate or
                  suspend your access to all or part of the Site or services,
                  with or without notice, for any reason, including without
                  limitation breach of these Terms, suspected fraudulent or
                  abusive activity, or conduct that we determine to be harmful
                  to other users, us, or third parties. Upon termination, your
                  right to use the services will immediately cease, and any
                  unused credits may be forfeited without refund.
                </p>
              </div>

              <div>
                <h2>Credits and Usage</h2>
                <p>
                  Our services operate on a credit-based system. Credits are
                  purchased in advance and consumed when you use the FMEA
                  generation features. Credits are non-transferable, have no
                  cash value, and cannot be exchanged or redeemed for cash.
                  Unused credits do not expire unless your account is
                  terminated.
                </p>
                <p mt="2">
                  We reserve the right to modify credit pricing, credit
                  consumption rates, or the features available for credit
                  redemption at any time. Such changes will not affect credits
                  already purchased but may affect how future credits are priced
                  or consumed.
                </p>
              </div>

              <div>
                <h2>Payments and Billing</h2>
                <p>
                  All credit purchases are processed by{' '}
                  <strong>Stripe, Inc.</strong>, a third-party payment
                  processor. By making a purchase, you agree to Stripe&apos;s{' '}
                  <a
                    className="font-semibold text-gray-darker hover:underline"
                    href="https://stripe.com/legal/consumer"
                    rel="noopener noreferrer"
                    target="_blank">
                    Terms of Service
                  </a>
                  . All prices are listed in US Dollars (USD). You are
                  responsible for any applicable taxes.
                </p>
                <p mt="2">
                  You are responsible for providing accurate billing
                  information. We reserve the right to suspend or terminate
                  access to paid features if payment cannot be processed or is
                  disputed fraudulently.
                </p>
              </div>

              <div>
                <h2>Refund Policy</h2>
                <p>
                  All purchases of credits and digital services are final and
                  non-refundable upon delivery. Given that our services involve
                  AI-generated content that is delivered immediately upon
                  purchase, refunds are not available once credits have been
                  issued to your account. In the event of a verified technical
                  failure attributable to our platform, we may, at our sole
                  discretion, issue replacement credits. To report such issues,
                  please contact{' '}
                  <a
                    className="font-semibold text-gray-darker hover:underline"
                    href="mailto:support@fmeatool.ai">
                    support@fmeatool.ai
                  </a>
                  .
                </p>
              </div>

              <div>
                <h2>Third-Party Links</h2>
                <p>
                  This Site may contain links to third-party websites or
                  services (including our own application app.fmeatool.ai) that
                  are not owned or controlled by this Site&apos;s specific
                  terms. We assume no responsibility for the content, privacy
                  policies, or practices of any third-party websites.
                </p>
              </div>

              <div>
                <h2>Governing Law</h2>
                <p>
                  These Terms shall be governed by and construed in accordance
                  with the laws of the{' '}
                  <strong>State of Delaware, United States</strong>, without
                  regard to its conflict of law provisions.
                </p>
              </div>

              <div>
                <h2>Changes to Terms</h2>
                <p>
                  We reserve the right to modify these Terms at any time.
                  Changes will be effective immediately upon posting to this
                  Site. Your continued use of the Site after any changes
                  constitutes your acceptance of the new Terms.
                </p>
              </div>

              <div>
                <h2>Severability</h2>
                <p>
                  If any provision of these Terms is found to be unenforceable
                  or invalid, that provision shall be limited or eliminated to
                  the minimum extent necessary so that these Terms shall
                  otherwise remain in full force and effect.
                </p>
              </div>

              <div>
                <h2>Dispute Resolution and Arbitration</h2>
                <p>
                  <strong>Binding Arbitration:</strong> Any dispute, claim, or
                  controversy arising out of or relating to these Terms or the
                  breach, termination, enforcement, interpretation, or validity
                  thereof, including the determination of the scope or
                  applicability of this agreement to arbitrate, shall be
                  determined by arbitration in Delaware before a single
                  arbitrator. The arbitration shall be administered by JAMS
                  pursuant to its Comprehensive Arbitration Rules and
                  Procedures. Judgment on the award may be entered in any court
                  having jurisdiction.
                </p>
                <p mt="2">
                  <strong>Class Action Waiver:</strong> YOU AND MAUDLIN WORKS,
                  LLC AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN
                  YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR
                  CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE
                  PROCEEDING. Unless both you and the Company agree otherwise,
                  the arbitrator may not consolidate more than one person&apos;s
                  claims and may not otherwise preside over any form of a
                  representative or class proceeding.
                </p>
                <p mt="2">
                  <strong>Opt-Out:</strong> You may opt out of this arbitration
                  agreement by sending written notice to{' '}
                  <a
                    className="font-semibold text-gray-darker hover:underline"
                    href="mailto:support@fmeatool.ai">
                    support@fmeatool.ai
                  </a>{' '}
                  within thirty (30) days of first accepting these Terms. Your
                  notice must include your name, address, and a clear statement
                  that you wish to opt out of this arbitration agreement.
                </p>
              </div>

              {/* Contact Us */}
              <div>
                <h2>Contact Us</h2>
                <p>
                  If you have any questions about these Terms of Use, please
                  contact us:
                </p>

                <ul list="disc" mt="4" pl="6" space-y="2">
                  <li>
                    By email:{' '}
                    <a
                      className="text-primary hover:underline font-semibold"
                      href="mailto:support@fmeatool.ai">
                      support@fmeatool.ai
                    </a>
                  </li>
                  <li>Company: Maudlin Works, LLC (Delaware, US)</li>
                </ul>
              </div>
            </div>
          </div>
        </Container>
      </div>
    </>
  )
}

export default TermsOfUse
