import { Container, SeoHead } from '~/components'

const TermsOfUse = () => {
  return (
    <>
      <SeoHead
        description="Read the Terms of Use for the fmeatool.ai website operated by Maudlin Works, LLC."
        title="Terms of Use | FMEA Tool"
      />

      <div py="lg:40 30">
        <Container>
          <div
            bg="gray-light"
            leading="relaxed"
            max-w="5xl"
            mx="auto"
            p="y-10 sm:x-10 x-4"
            rounded="2xl"
            shadow="xl"
            text="sm:base sm">
            <div mb="12" text="center">
              <h1
                color="gray-darker "
                font="bold"
                mb="4"
                text="3xl sm:5xl"
                tracking="tight">
                Terms of Use
              </h1>

              <p text="base gray-dark">Last updated: January 12, 2026</p>
            </div>

            <div
              className="[&_h2]:color-gray-darker [&_h2]:font-semibold [&_h2]:mb-4 [&_h2]:text-xl sm:3xl "
              color="gray-dark"
              space-y="8">
              <div>
                <h2>Agreement to Terms</h2>
                <p>
                  Welcome to <strong>fmeatool.ai</strong> (the
                  &quot;Site&quot;), operated by{' '}
                  <strong>Maudlin Works, LLC</strong> (&quot;Company,&quot;
                  &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). By
                  accessing or using this Site, you agree to be bound by these
                  Terms of Use. If you do not agree to these terms, please do
                  not use the Site.
                </p>
              </div>

              <div>
                <h2>Informational Purpose Only</h2>
                <p>
                  The content provided on this Site is for general informational
                  and marketing purposes regarding our FMEA Tool software.
                  Please note that the actual software service is hosted
                  separately at{' '}
                  <span className="font-semibold">app.fmeatool.ai</span> and is
                  subject to its own separate Terms of Service and Subscription
                  Agreement.
                </p>
              </div>

              <div>
                <h2>Intellectual Property</h2>
                <p>
                  All content, features, and functionality on this Site
                  (including but not limited to the &quot;FMEA Tool&quot; brand,
                  logos, 3D graphics, text, and design) are the exclusive
                  property of Maudlin Works, LLC and are protected by United
                  States and international copyright, trademark, and other
                  intellectual property laws. You may not reproduce, distribute,
                  or create derivative works from any part of this Site without
                  our express written permission.
                </p>
              </div>

              <div>
                <h2>Disclaimer Regarding AI Features</h2>
                <p>
                  Our Site describes software that utilizes Artificial
                  Intelligence (AI). While we strive to describe our product
                  accurately, AI technologies are probabilistic in nature. We do
                  not guarantee that the marketing descriptions on this Site
                  will align perfectly with every output generated by the
                  software in unique or complex edge cases.
                </p>
              </div>

              <div>
                <h2>Limitation of Liability</h2>
                <p>
                  To the fullest extent permitted by law, Maudlin Works, LLC
                  shall not be liable for any indirect, incidental, special,
                  consequential, or punitive damages arising out of or related
                  to your use of this Site (the landing page). The information
                  on the Site is provided on an &quot;as is&quot; basis without
                  warranties of any kind.
                </p>
              </div>

              <div>
                <h2>Third-Party Links</h2>
                <p>
                  This Site may contain links to third-party websites or
                  services (including our own application app.fmeatool.ai) that
                  are not owned or controlled by this Site’s specific terms. We
                  assume no responsibility for the content, privacy policies, or
                  practices of any third-party websites.
                </p>
              </div>

              <div>
                <h2>Governing Law</h2>
                <p>
                  These Terms shall be governed by and construed in accordance
                  with the laws of the{' '}
                  <strong>State of Delaware, United States</strong>, without
                  regard to its conflict of law provisions.
                </p>
              </div>

              {/* Contact Us */}
              <div>
                <h2>Contact Us</h2>
                <p>
                  If you have any questions about these Terms of Use, please
                  contact us:
                </p>

                <ul list="disc" mt="4" pl="6" space-y="2">
                  <li>
                    By email:{' '}
                    <a
                      className="text-primary hover:underline font-semibold"
                      href="mailto:support@fmeatool.ai">
                      support@fmeatool.ai
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </Container>
      </div>
    </>
  )
}

export default TermsOfUse
